name: "air_boltic_analytics"
version: "1.0.0"
config-version: 2

profile: "air-boltic-analytics"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  air_boltic_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts